name: Issue Labeler

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run github/issue-labeler
      uses: github/issue-labeler@v3.4
      with:
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
        repo-token: ${{ github.token }}
        include-title: 0
        include-body: 1
        sync-labels: 0
        issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}

permissions:
  issues: write
  pull-requests: write
