name: Issue Labeler

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

permissions:
    issues: write
    pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: .github

    - name: Run github/issue-labeler
      uses: github/issue-labeler@v3.4
      with:
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
        repo-token: ${{ github.token }}
